### ISSUE TITLE
problem on Training on Caltech (RPN)

### ISSUE THREAD

**Issue by whj363636** [zhangliliang/RPN_BF#43]
Hello @zhangliliang!

When I follow the **Training on Caltech (RPN)** instruction, I meet this problem: 

```
Preparing the results for Caltech evaluation ...Done.Cannot find an exact (case-sensitive) match for 'dbInfo'

The closest match is: dbinfo in /usr/local/MATLAB/R2014/toolbox/wavelet/wavelet/dbinfo.m

Error in dbEval_RPNBF (line 102)
  [~,set]=dbInfo(dataName); set=['/set' int2str2(set(1),2)];

Error in Faster_RCNN_Train.do_proposal_test_caltech (line 62)
    dbEval_RPNBF;

Error in script_rpn_pedestrian_VGG16_caltech (line 53)
Faster_RCNN_Train.do_proposal_test_caltech(conf_proposal, model.stage1_rpn, dataset.imdb_test, dataset.roidb_test, cache_name, method_name);

Error in run (line 63)
evalin('caller', [script ';']);
```

Do you have any idea to fix it? Thanks a lot!

**Comment by whj363636** [comment]
I have already fixed the bug above, but another happened when Evaluating:
```
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information, click <a href="matlab:opengl('problems')">here</a>.
Warning: MATLAB cannot use OpenGL for printing when started with the '-nodisplay' option.
> In graphics/private/inputcheck at 143
  In print at 156
  In savefig at 226
  In dbEval_RPNBF>plotExps at 229
  In dbEval_RPNBF at 125
  In do_proposal_test_caltech at 62
  In script_rpn_pedestrian_VGG16_caltech at 53
  In run at 63
log4j:WARN No appenders could be found for logger (org.apache.fop.util.ContentHandlerFactoryRegistry).
log4j:WARN Please initialize the log4j system properly.
gs: /usr/local/MATLAB/R2014/bin/glnxa64/libtiff.so.5: no version information available (required by /usr/lib/libgs.so.9)
```

**Comment by BastianBlossom** [comment]
Hello @whj363636 
I have another issue with Training on Caltech (RPN), when preparing the image proposal, I am getting an out of memory issue, since in the file proposal_prepare_image_roidb_caltech.m for each training image a bbox_targets of size 23400x5 is added. Did u have any problem like this, if there how do you solved that?

**Comment by whj363636** [comment]
@BastianBlossom 
Hello, In fact I also met with memory problem when I run the experiment. But I fixed it just by clearing the cache and rerunning it. I don't know whether it will make any sense for you. You can have a try.

**Comment by BastianBlossom** [comment]
Thanks @whj363636, I gone for increasing the swap memory space and it worked for me.

**Comment by BastianBlossom** [comment]
Hello @whj363636 ,
Are you getting the same result as mentioned in the paper? " Is Faster R-CNN Doing Well for Pedestrian Detection?".  I am getting only a missrate of 49% for the proposal testing itself (RPN)

**Comment by whj363636** [comment]
@BastianBlossom hey, 
Actually I can run the experiment successfully without any error, but I couldn't see the miss rate at the end of the testing for the warning in matlab nodispaly mode. Have you ever met with this problem and fixed it? I'm in Linux  and run matlab by terminal.
By the way, I got ~10 miss rate in the second experiment(RPN-BF) at the last but one tesing turn(the last turn can't be seen since the warning I mentioned above), So I think the first one should be right.

**Comment by BastianBlossom** [comment]
Hey @whj363636 , 
I have copied the final detection boxes and scores and then checked the miss rate using the P.Dollar code for "acfTest.m".  Earlier you have mentioned about clearing the cache, have you cleared the cache in Matlab command window or in the Terminal? Also which command have you used?. I am still having the memory problem

**Comment by whj363636** [comment]
@BastianBlossom Sorry for replyng late.
In fact, I have been dealing with "out of memory" few days and still no solution. So, ignoring my answers about clearing cache before because it just applise to another "out of memory" problem I met, not about roidb preparing.

These days I googled for answers and **it must be something wrong with parfor and its workers**. Maybe decrease the number of workers will run correctly, but I haven't found the "local file" and change it in Linux yet.

**But after modifying source code, then I meet this problem**. So I think the reason why you can't run "in memory" must be something about "workers"(too much). Just guess.

**Comment by whj363636** [comment]
@BastianBlossom Hey,
I fixed the problem today. In case you're struggling in the trouble, I just give my solution(not absolutely right but works) about that below(if you have solved it, ignore them):
1. run the experiment on computer(or cluster) with bigger memory
2. no `do_val`
3. skip more empty image for saving memory
4. cut network

**Comment by chr10003566** [comment]
@whj363636 
I am trying to follow the **Training on Caltech (RPN)** instruction, I meet some problems.  I can't understand which is the proper folder from the website(http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/).  Maybe I need to read that two paper. I will be very grateful if you can tell me some tips. Thank you so much.
